name: Build QTBase for Windows
  
agent:
  type: Unity::VM
  image: cds-ops/win10-vs2017:stable
  flavor: b1.large

artifacts:
  qtbase-windows.zip:
    paths:
      - build/builds.7z

commands:
  - perl build.pl --arch=64

triggers:
  pushes:
    only:
      - qtbuild.5.9.7
