name: Build QTBase for Linux
  
agent:
  type: Unity::VM
  image: tokyo-dev/qt-linux-build-image:latest
  flavor: m1.large

artifacts:
  qtbase-linux.zip:
    paths:
      - build/builds.7z

commands:
  - 7z x /toolchains/PlatformD*/Linux/Ex*/NonR*/g*/builds.7z -o/toolchains/gcc
  - export PATH=$PATH:/toolchains/gcc/bin CC="x86_64-ubuntu14.04-linux-gnu-gcc" CXX="x86_64-ubuntu14.04-linux-gnu-g++" LD="x86_64-ubuntu14.04-linux-gnu-gcc" AR="x86_64-ubuntu14.04-linux-gnu-ar" RANLIB="x86_64-ubuntu14.04-linux-gnu-ranlib" ARFLAGS="-r"
  - perl build.pl --arch=64

triggers:
  pushes:
    only:
      - qtbuild.5.9.7
