name: Build QTBase for Linux
  
agent:
  type: Unity::VM
  image: slough-ops/ubuntu-16.04-base:stable
  flavor: m1.large

artifacts:
  qtbase-linux.zip:
    paths:
      - build/builds.7z

commands:
  - perl build.pl --arch=64

triggers:
  pushes:
    only:
      - qtbuild.5.9.7
