name: Build QTBase for Linux
  
agent:
  type: Unity::VM
  image: cds-ops/ubuntu-18.04-agent:latest
  flavor: m1.large

artifacts:
  qtbase-linux.zip:
    paths:
      - build/builds.7z

commands:
  - sudo apt-get install gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
  - perl build.pl --arch=64

triggers:
  pushes:
    only:
      - qtbuild.5.9.7
